### ISSUE TITLE
Workflow #1 Introduction to new users: Cloud Sync from HydroShare Resource

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_on_jupyter#20]
Workflow #1:  Cloud = don't install anything, start from a HydroShare link, move files back and forth from CUAHSI JHserver to HydroShare.

1. Go to the [Olin Sync HydroShare resource](https://www.hydroshare.org/resource/37f83d3a43c648aa89db6a5c16e60b8e/).   
2.  Click on Open With.  Select MyBinder.   You should see a spinning wheel like this. Wait to launch the server.
![image](https://user-images.githubusercontent.com/4108369/80415511-80bc2d80-8887-11ea-8934-c714d95f9e6d.png)

3. Add a text file using Sync.

**Comment by ChristinaB** [comment]
How does the user get to Sync??

the user currently need to know how to open sync.  We need a big pretty sync button. 
![image](https://user-images.githubusercontent.com/4108369/80415625-a47f7380-8887-11ea-87e0-54bb4d0a5ac8.png)

edit the URL to 
![image](https://user-images.githubusercontent.com/4108369/80415755-d0025e00-8887-11ea-90c7-d9c8560450c7.png)

**Comment by ChristinaB** [comment]
3. Login to HydroShare using Sync.

Shouldn't this be the thing that happens next? I don't want to see the server directory view. 
![image](https://user-images.githubusercontent.com/4108369/80415889-1061dc00-8888-11ea-9ba2-751376dee5f3.png)

**Comment by ChristinaB** [comment]
After login your data will be loaded:
![image](https://user-images.githubusercontent.com/4108369/80416480-0d1b2000-8889-11ea-949d-dbc1c780a678.png)

**Comment by ChristinaB** [comment]
Testing Poll: 
1) Should we have a Sync Button on the JupyterHub server folder view? (and other buttons)
OR
2) Should the user be directed straight to Sync view (change tree to sync in URL)

**Comment by ChristinaB** [comment]
@jtpollak  This is the workflow we want to turn into a lovely newsletter spread.  Discussing with @Castronova to advertise sometime in May.

**Comment by aaraney** [comment]
closing, as this is stale. the concerns raised in this issue have now been resolved through the new implementation of the software. now the software is an integrated jupyter lab widget plugin, so the sync app is accessible via the jupyter lab launcher.
