### ISSUE TITLE
Add buttons to CUAHSI Juptyer Hub - demo with Sync

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_on_jupyter#21]
Let's generalize this for Lab and Sync and any Web app.  @sblack-usu can you like your general hydroshare issue for generating the URL to this issue?

**Comment by sblack-usu** [comment]
If we're configuring per resource, I think building a MyBinder Sync web app connector is reasonable without adding extra configuration for modifying the url.  Then just link the resource to the MyBinder Sync web app connector with the appkey.

There was also the suggestion of opening directly to a notebook. With current functionality you can configure a file level url that shows up when right-clicking on a file in a resource.  See https://www.hydroshare.org/terms/#AppURLPattern . The HS_FILE_PATH is available, you should be able to use that as the query parameter value for urlpath that Binder provides.  I can put together a demo resource for this if you'd like.

**Comment by sblack-usu** [comment]
I copied the MyBinder web app connector and put in a file level url  that launches on .ipynb files.  You can see it here. https://www.hydroshare.org/resource/bb377127f70b45ab9ec1c5a7cef98783/

If you add the resource to your open with list, then go to a resource with a notebook file (.ipynb), right click on the file and select the web app.  It launch the resource into MyBinder and open directly into the notebook.

I put this together for a demo, I think we should just add this configuration to the MyBinder web app connector.  Below is the necessary configuration to do so.
![image](https://user-images.githubusercontent.com/35820390/80611585-0363fa80-89f8-11ea-8b8a-68fa9604d9d9.png)

**Comment by aaraney** [comment]
marking this as stale and closing. I dont think this issue is being tracked in the correct repository.

**Comment by aaraney** [comment]
for clarity, there is no work on going to implement features involved in the above discussion.
