### ISSUE TITLE
Workflow #2: Software environment packaging for accessing Public Resources on JupyterHub

### ISSUE THREAD

**Issue by ChristinaB** [hydroshare/hydroshare_on_jupyter#22]
For example - https://github.com/hydroshare/hydroshare_jupyter_sync/tree/tony/packaging

**Comment by ChristinaB** [comment]
Testing next on jupyter.cuahsi.org

**Comment by aaraney** [comment]
closing, no longer relevant. this has been resolved in new versions of the software.

**Comment by aaraney** [comment]
for any users who find this issue, please see the [installation guide](https://github.com/hydroshare/hydroshare_on_jupyter/blob/master/README.md#installation).
