### ISSUE TITLE
Collapsible folders and drag-and-drop

### ISSUE THREAD

**Issue by kylecombes** [hydroshare/hydroshare_on_jupyter#27]
The code for collapsing and expanding folders in a `FilePane` is in place, but enabling it breaks certain drag and drop functionality. (Therefore, the code is currently disabled.)

# Reproducing
1. Uncomment the commented-out code setting `classNames` in `FilePane.tsx#generateFolderNameTableCell`
2. Uncomment the `&& this.state.expandedFolders.has(folder.path)` in the `if` statement in `FilePath.tsx#generateFolderElement`
3. Launch/refresh the web app
4. Open the `ResourcePage` for a resource
5. Create a new folder (Folder A) in the workspace
6. Create a second new folder (Folder B) in the workspace
7. Create a new file (File 1)
8. Drag Folder B into Folder A
9. Expand Folder A so that Folder B is visible again
10. Attempt to drag File 1 into Folder B

Only Folder A should be recognized as a valid Droppable.

However, if you expand Folder A immediately after creating it (step 5) and then continue with the steps outlined, Folder B should be recognized as a valid Droppable and you should be able to move File 1 into Folder B.

The same behavior can be observed if you reload the page, expand folders, and attempt to drop items into their newly rendered subfolders.

This could be an issue with `react-beautiful-dnd`. I started trying to recreate the issue in CodeSandbox (a requisite step in submitting an issue to that repo), but I didn't finish.

# Affected Files
* `FilePane.tsx`

**Comment by aaraney** [comment]
closing, as this is stale. drag-and-drop has not been implemented as of `0.1.3`. This is a feature that I would like to implement in the future. When that time comes, I will link this issue to any related issues.
