### ISSUE TITLE
Slow OPTIONS request handling (sometimes)

### ISSUE THREAD

**Issue by kylecombes** [hydroshare/hydroshare_on_jupyter#32]
This is an intermittent issue. Sometimes the OPTIONS requests to the backend take a very long time (~30s) to resolve. This should be extremely fast, since all it should be doing is setting some headers and transmitting an empty response.

# Files Affected
* `hydroshare_jupyter_sync/server.py`

**Comment by aaraney** [comment]
Hmm that is odd. From the above comment I am assuming this behavior is from the client's perspective using the frontend web app. Ill make sure to cover this case in the bankend's unit tests.

**Comment by aaraney** [comment]
closing, no longer relevant. this has been resolved in new versions of the software.
