### ISSUE TITLE
Add ability to create file/folder inside folder

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#34]
## Current Behavior
Currently users need to create a file or folder in the main folder and then drag that file/folder into the folder they want it in.

## Desired Behavior
Ability to create a file/folder directly into another folder. Perhaps adding an option on the right click menu for folders to create a new file/folder is the way to do this.

**Comment by aaraney** [comment]
closing, as this is stale. I like this feature idea, so this may be reopened/linked in the future if this feature is to be added.
