### ISSUE TITLE
Add "Remove from workspace" button on resource page

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#35]
## Current behavior
If a user wants to clear their workspace, they have two options:

1. go to the page with all of their resources and select their resource and click "remove from workspace". The resource page has a button to redirect them to the all resources page for them to do this.
2. on the resource page, select all files in their workspace and click delete

## Desired behavior
The ability to remove their resource from their workspace directly from the resource page. This action deletes all files in the workspace.

**Comment by aaraney** [comment]
closing, no longer relevant.
