### ISSUE TITLE
Rename the workspace location to "hydroshare_resource_data"

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#38]
## Current behavior
Currently all workspace versions of HydroShare resources are stored under a "local_hs_resources" folder in whatever folder is specified in the config file.

## Desired behavior
Rename this to "hydroshare_resource_data". This is a more descriptive name and doesn't have "local" in it which can be confusing when running this in a Binder instance.

## Files affected
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/resource_local_data.py#L225-L226

https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/resource_manager.py#L38-L39

There may be more instances of `local_hs_resources` in the code, so doing a search for it would be best to be thorough

**Comment by aaraney** [comment]
This has been resolved in new software versions.
