### ISSUE TITLE
Speed up getting list of user resources

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#39]
## Current behavior
Getting list of user's resources takes time

## Desired behavior
Speed up this process

## Affected files
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/resource_manager.py#L180-L188

**Comment by aaraney** [comment]
This has been resolved in new software versions.
