### ISSUE TITLE
Properly set CORS Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#40]
## Current behavior
Currently any website can make a request to the backend.

## Desired behavior
We want it to say that only the frontend can make requests, in which case the asterisk would be replaced by the domain JupyterHub is being run on.

## Affected files
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/server.py#L49-L57

**Comment by aaraney** [comment]
closing, no longer relevant. this has also been resolved.
