### ISSUE TITLE
Optimize delete functions

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#41]
## Current status
Delete function is long and code is repeated in `ResourceHydroShareFilesRequestHandler` and `ResourceLocalFilesRequestHandler`.

## Desired behavior
Move some of the logic to optimize the functions and clean up the code.

## Affected files
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/server.py#L209-L214

https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/server.py#L343-L349

**Comment by aaraney** [comment]
closing, no longer relevant.
