### ISSUE TITLE
Add ability to copy file

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#42]
## Current behavior
If a user wanted to copy a file, they would need to download a file, and reupload it to their workspace (and then sync it to HydroShare if they wanted to copy a HydroShare file).

## Desired behavior
Add the ability to copy a file in the workspace and from HydroShare.

## Affected files
On the backend:
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/server.py#L497-L501

https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/hydroshare_jupyter_sync/server.py#L497-L501

On the frontend, this would probably be an addition to the context menu for each file.
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/webapp/src/components/FilePane.tsx#L184-L208

**Comment by aaraney** [comment]
closing, no longer relevant. I like this feature idea though. may reopen in future if this it to be added.
