### ISSUE TITLE
Automatically expand folders that contain filtered files

### ISSUE THREAD

**Issue by Elepert** [hydroshare/hydroshare_on_jupyter#46]
## Current behavior
Currently, all folders are automatically expanded, so this isn't an issue. However, when https://github.com/hydroshare/hydroshare_jupyter_sync/issues/27 will be resolved, when users search for a file, the folder containing it will not expand automatically. The user will see a folder and not the file/folder they're searching for.

## Desired behavior
When searching for a file/folder, have all parent folders automatically expand to reveal the file/folder that's searched for.

## Affected files
https://github.com/hydroshare/hydroshare_jupyter_sync/blob/f739fe864a6e64d8179a822d2fbf1493e8ee13e5/webapp/src/components/FilePane.tsx#L152-L170

**Comment by aaraney** [comment]
closing, no longer relevant.
