### ISSUE TITLE
OnClick of Workspace File is redirecting to wrong url 

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#51]
To open the Workspace File in Jupyter Notebook, OnClick is redirecting to a url that has 'undefined' as a parameter in url. 

For example, clicking on 'CampusResidentialWaterUseAnalysis' redirects to : http://localhost:3000/resources/undefined/4352ca1a81b949efb12116597b867339/4352ca1a81b949efb12116597b867339/data/contents/CampusResidentialWaterUseAnalysis.ipynb

<img width="1140" alt="Screen Shot 2020-06-11 at 5 40 24 PM" src="https://user-images.githubusercontent.com/36516546/84466793-7ab3bd80-ac37-11ea-9cd8-c319f967884e.png">
<img width="1200" alt="Screen Shot 2020-06-11 at 5 40 07 PM" src="https://user-images.githubusercontent.com/36516546/84466805-80110800-ac37-11ea-853d-9ae383ef7942.png">

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue.
