### ISSUE TITLE
Cancel button should be disabled for Login Prompt

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#58]
Cancel button should be disabled on the Login Prompt.

<img width="1140" alt="Screen Shot 2021-03-23 at 2 30 36 PM" src="https://user-images.githubusercontent.com/36516546/112214560-f68a5f80-8be4-11eb-92b0-a6ce2ca9e50b.png">

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue.
