### ISSUE TITLE
Error message when opening workspace files 

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#61]
The application throws an error message if the files are not downloaded in the workspace. Instead of throwing an error, a notification or popup will be helpful. 

![image](https://user-images.githubusercontent.com/36516546/112218360-39e6cd00-8be9-11eb-945a-de6a533ee060.png)

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue.
