### ISSUE TITLE
Adjust width of cells dynamically based on the content

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#64]
Cell width under HydroShare and Workspace file need to be adjusted to view long text.

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/36516546/112220216-9c40cd00-8beb-11eb-86d6-4dee9efc311e.png">

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue.
