### ISSUE TITLE
Notebook files do not open if "jupyter notebook" command runs from a directory other than the home directory.

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#65]
Notebook files do not open if "jupyter notebook" command does not run from the Home directory. It is not able to locate the relative path of the resource data saved locally.

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue. To the root of this issue, a toast message is now displayed to the used when they try to open a file but the jupyter session was started from a directory that is not a parent of the `DATA` directory where resources are stored upon download.
