### ISSUE TITLE
Improper CSS for Preferences Drop-down

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#67]
Preferences Drop-down at the menu bar have improper CSS. It needs to be aligned with the other buttons.

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/36516546/112222508-3f92e180-8bee-11eb-972d-123abb523bfe.png">

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue.
