### ISSUE TITLE
Remove "Open in HydroShare" button 

### ISSUE THREAD

**Issue by soumyapurohit** [hydroshare/hydroshare_on_jupyter#68]
The "Open in HydroShare" button should be disabled if any file is selected under the HydroShare Files column. As Open in HydroShare opens up the HydroShare resource instead of individual HydroShare files.

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/36516546/112223035-f3946c80-8bee-11eb-8646-19c5493f2746.png">

**Comment by aaraney** [comment]
Given the extent of the frontend changes, I am going to close this issue.
